[aws_group]
server1 ansible_host=13.57.31.250
server2 ansible_host=13.52.230.155
server3 ansible_host=54.183.201.181

[ubuntu_group]
server4 ansible_host=54.151.37.27
server5 ansible_host=54.176.201.180
server6 ansible_host=54.177.171.80

[aws_group:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=mykeypair.pem

[ubuntu_group:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=mykeypair.pem


  